export const productList = [
    {title: "Super Mario Maker 2",
    id:"Super Mario Maker 2",
    price:11250,
    stock: 5,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadores. Podrás disfrutar de una experiencia inigualable, ya que te permite jugar con tus amistades y compartir momentos inolvidables. Diversión sin fronteras. Podrás compartir cada juego con personas de todo el mundo, ya que es posible conectarse de manera online.",
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_757148-MLA40917205776_022020-O.webp",
    Url2: "https://http2.mlstatic.com/resources/frontend/ft-extended-v00/assets/vectorial/default.svg",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 2.8 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: Sí"},
    
    {title: "Super Mario 3D World",
    id:"Super Mario 3D World",
    price:11899,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadoresPodrás disfrutar de una experiencia inigualable.",
    stock: 4,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_940603-MLA44886780516_022021-O.webp",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 215 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: Mo"},
    
    {title: "Mario Party SuperStars",
    id:"Mario Party SuperStars",
    price:11938,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadoresPodrás disfrutar de una experiencia inigualable.",
    stock: 6,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_738842-MLA48119679478_112021-O.webp",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 20 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: Sí"},
    
    {title: "Super Smash Bros  Ultimate",
    id:"Super Smash Bros  Ultimate",
    price:12325,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadoresPodrás disfrutar de una experiencia inigualable.",
    stock: 10,
    pictureUrl: "https://www.cjs-cdkeys.com/product_images/img/o/17012.jpg",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 8 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: Sí"},
    
    {title: "Zelda Link's Awakening",
    id:"Zelda Link's Awakening",
    price:10499,
    detailss: "Los juegos de la franquicia The Legend of Zelda marcaron un antes y después en el género de aventura. Convertite en Link para vencer a los villanos que hicieron de un pacífico reino un lugar inmerso en las tinieblas.",
    stock: 20,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_968049-MLA40927047075_022020-O.webp",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 30 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: No"}
    
]

